FORMAT: 1A
HOST: https://api.thedogapi.co.uk/v2

# DogAPI

This is a simple API for retrieving and/or posting images of dogs. There are plenty of these available for cats, so why not one for dogs?

## Get dog [/dog.php{?limit,id}]

+ Parameters

    + limit (optional) - The amount of dog images you want to get. Defaults to 1, and has a maximum of 20.
    + id (optional) - The ID of a specific dog that you want to get. If specified, limit will be ignored.

### Get a random dog [GET]

+ Response 200 (application/json)

        {
            "data": [
                {
                    "id": "3UHaLkCuZvA",
                    "url": "https://i.redd.it/yz95pef6gn6z.jpg",
                    "time": "2017-06-30T03:57:20.073537",
                    "format": "jpeg",
                    "checked": 1,
                    "verified": 1
                }
            ],
            "count": 1,
            "error": null,
            "api_version": "v2",
            "response_code": 200
        }